### ISSUE TITLE
Child templates missing

### ISSUE THREAD

**Issue by dalisay** [aws-quickstart/quickstart-compliance-hipaa#4]
Can't find the child templates in 'submodules'?

https://github.com/aws-quickstart/quickstart-compliance-hipaa/tree/master/submodules

**Comment by henrym6003** [comment]
Any chance these submodules will be included in this repo? 

It appears you can access the source template files using the below steps:

1. Create A New Stack
2. Specify an Amazon S3 template URL . (using the URLs below)
3. View/Edit template in Designer



- https://aws-quickstart.s3.amazonaws.com/quickstart-compliance-hipaa/submodules/quickstart-compliance-common/templates/iam.template
- https://aws-quickstart.s3.amazonaws.com/quickstart-compliance-hipaa/submodules/quickstart-compliance-common/templates/logging.template
- https://aws-quickstart.s3.amazonaws.com/quickstart-compliance-hipaa/submodules/quickstart-compliance-common/templates/vpc-production.template
- https://aws-quickstart.s3.amazonaws.com/quickstart-compliance-hipaa/submodules/quickstart-compliance-common/templates/vpc-management.template
- https://aws-quickstart.s3.amazonaws.com/quickstart-compliance-hipaa/submodules/quickstart-compliance-common/templates/config-rules.template
- https://aws-quickstart.s3.amazonaws.com/quickstart-compliance-hipaa/submodules/quickstart-compliance-common/templates/application.template

**Comment by agamzn** [comment]
This was fixed in https://github.com/aws-quickstart/quickstart-compliance-hipaa/commit/da0723cca32358924ed445f44ac78514c6af3b2c and is available in the develop branch. It should be available in master shortly.
