### ISSUE TITLE
CloudWatch Alarms INSUFFICIENT_DATA

### ISSUE THREAD

**Issue by jeffshaikh** [aws-quickstart/quickstart-compliance-hipaa#6]
The autoscale group cloudwatch alarms are stuck at the state of INSUFFICIENT_DATA and there doesn't appear to be any data collected while viewing the alarm graphs in the console. This remains in this state for days, even through the Period is set for 60 secs.

**Comment by agamzn** [comment]
This should be resolved via #8  :)

**Comment by jeffshaikh** [comment]
Yes, fixed. Alarms states are behaving normally now. Thanks.
